OCAMLMAKEFILE = ../OCamlMakefile

OCAMLNLDFLAGS = -unsafe -noassert
OCAMLNCFLAGS = -unsafe -noassert

CC = gcc

INCDIRS = ../matrix ../neural_net ../pgm
LIBS   = str matrix neural_net pgm

SOURCES = decoder.ml 
RESULT  = decoder

-include $(OCAMLMAKEFILE)
